In [110]:
# Data Preprocessing
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
# Importing the dataset
datasets = pd.read_csv('/content/drive/MyDrive/WorkSpace2/ML/01_ Data_Preprocessing/Data.csv')
print(len(datasets))
datasets.head()

10


Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes

In [111]:
len( datasets[datasets['Age'].isnull()==True])

1

In [112]:
#datasets.iloc[:,[0,1,3]]
X=datasets.iloc[:,1:-1].values
Y=datasets.iloc[:,-1].values
print(X.ndim,Y.ndim)
X

2 1


array([[4.4e+01, 7.2e+04],
       [2.7e+01, 4.8e+04],
       [3.0e+01, 5.4e+04],
       [3.8e+01, 6.1e+04],
       [4.0e+01,     nan],
       [3.5e+01, 5.8e+04],
       [    nan, 5.2e+04],
       [4.8e+01, 7.9e+04],
       [5.0e+01, 8.3e+04],
       [3.7e+01, 6.7e+04]])

In [113]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
X[:,0:3]=imputer.fit_transform(X[:,0:3])
X[:,0:3]

array([[4.40000000e+01, 7.20000000e+04],
       [2.70000000e+01, 4.80000000e+04],
       [3.00000000e+01, 5.40000000e+04],
       [3.80000000e+01, 6.10000000e+04],
       [4.00000000e+01, 6.37777778e+04],
       [3.50000000e+01, 5.80000000e+04],
       [3.87777778e+01, 5.20000000e+04],
       [4.80000000e+01, 7.90000000e+04],
       [5.00000000e+01, 8.30000000e+04],
       [3.70000000e+01, 6.70000000e+04]])

In [114]:
from sklearn.preprocessing import OneHotEncoder,LabelEncoder
label_encoder=LabelEncoder()
Y=label_encoder.fit_transform(Y)
Y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
"""binary_enc = OneHotEncoder() #.fit(X)
X_encoded=binary_enc.fit_transform(X).toarray()
X_encoded"""

In [115]:
from sklearn.preprocessing import StandardScaler
stdscaler=StandardScaler()
X_all=stdscaler.fit_transform(X)
X_all

array([[ 7.58874362e-01,  7.49473254e-01],
       [-1.71150388e+00, -1.43817841e+00],
       [-1.27555478e+00, -8.91265492e-01],
       [-1.13023841e-01, -2.53200424e-01],
       [ 1.77608893e-01,  6.63219199e-16],
       [-5.48972942e-01, -5.26656882e-01],
       [ 0.00000000e+00, -1.07356980e+00],
       [ 1.34013983e+00,  1.38753832e+00],
       [ 1.63077256e+00,  1.75214693e+00],
       [-2.58340208e-01,  2.93712492e-01]])

In [116]:
X_all[0,0]

0.758874361590019

In [117]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(X_all,Y,test_size=0.2,random_state=0)
print(len(x_train),len(x_test),len(y_train),len(y_test))

8 2 8 2
