##Data Loading and Visualization

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
# Decision Regression
# Importing the libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [3]:
# Importing the dataset
dataset = pd.read_csv('/content/drive/MyDrive/WorkSpace2/GIT/Machine_Learning/Tree_Classification/Social_Network_Ads.csv')
print(len(dataset))
dataset.head(5)

400


User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset['Purchased'].unique()

array([0, 1])

In [20]:
X = dataset.iloc[:, 2:4].values
y = dataset.iloc[:, 4].values
print(X[:5],y[:5])

[[   19 19000]
 [   35 20000]
 [   26 43000]
 [   27 57000]
 [   19 76000]] [0 0 0 0 0]


In [ ]:
"""import matplotlib.pyplot as plt
plt.scatter(X[0],y) """

In [21]:
# Splitting the dataset into the Training set and Test set
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

# Feature Scaling
"""from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)"""

'from sklearn.preprocessing import StandardScaler\nsc_X = StandardScaler()\nX_train = sc_X.fit_transform(X_train)\nX_test = sc_X.transform(X_test)'

##Train the Models

In [32]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [33]:
DTC=DecisionTreeClassifier()
print(DTC.fit(X_train,y_train))
y_pred_DTC=DTC.predict(X_test)
print(accuracy_score(y_test,y_pred_DTC))
confusion_matrix(y_test,y_pred_DTC)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=None, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=None, splitter='best')
0.9125


array([[54,  4],
       [ 3, 19]])

In [34]:
RFC=RandomForestClassifier()
print(RFC.fit(X_train,y_train))
y_pred_RFC=RFC.predict(X_test)
print(accuracy_score(y_test,y_pred_RFC) )
confusion_matrix(y_test,y_pred_RFC)

RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)
0.9375


array([[55,  3],
       [ 2, 20]])

In [17]:
y_test[10:15],y_pred_DTC[10:15]

(array([0, 0, 0, 0, 0]), array([0, 0, 0, 0, 0]))